training:
  name: 'cloud_train'
  use_wandb: True 
  data_path: 'dataset/mp4'
  learning_rate: 0.00001
  num_epochs: 30
  batch_size: 12
  epochs_per_stage: 2
  transition_epochs: 2
  initial_resolution: 4
  final_resolution: 256

weights:
  gan:
    real: 0.2
    fake: 0.6
    feature_matching: 0.2
    adversarial: 0.4
  perceptual:
    lpips: 1.0

